name: Update Image Timestamp

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with new timestamp
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|\(https://asukaforever.com/api/counter/AsukaCC_github?type=rule34\).*|\1&timestamp=${TIMESTAMP}|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with new timestamp"
          git push
